#!/usr/bin/env bash
# Update word list from shmookey's curated 5-letter words
# Run with: npm run update-words

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
SRC_DIR="$REPO_ROOT/src"
OUT_FILE="$SRC_DIR/words.ts"
URL="https://gist.githubusercontent.com/shmookey/b28e342e1b1756c4700f42f17102c2ff/raw/WORDS"

echo "Fetching word list from $URL..."
TEMP_FILE="$(mktemp)"
trap 'rm -f "$TEMP_FILE"' EXIT

if ! curl -sfL "$URL" > "$TEMP_FILE"; then
  echo "Error: Failed to fetch word list"
  exit 1
fi

# Filter: lowercase, alphabetic only, exactly 5 letters, deduplicate
WORDS=$(awk '{print tolower($0)}' "$TEMP_FILE" | grep -E '^[a-z]{5}$' | sort -u)

COUNT=$(echo "$WORDS" | wc -l | tr -d ' ')
if [ "$COUNT" -lt 2000 ]; then
  echo "Error: Got only $COUNT words, expected ~3100"
  exit 1
fi

# Format as TypeScript array with proper commas and line breaks
ARRAY=$(echo "$WORDS" | sed "s/.*/  '&',/" | paste -sd '\n' -)

cat > "$OUT_FILE" <<EOF
// Auto-generated by scripts/update-words.sh
// Source: https://gist.github.com/shmookey/b28e342e1b1756c4700f42f17102c2ff
// Curated intersection of Wikipedia 100k + US/UK dictionaries

export const WORDS: string[] = [
$ARRAY
];
EOF

echo "Updated $OUT_FILE with $COUNT words"