import { Puzzle } from "./types";

// Generated via scripts/generate-h0-diverse.cjs

export const PUZZLES: Puzzle[] = [
  { h: ["afire", "raise", "shyly"], v: ["acres", "icily", "enemy"] },
  { h: ["offal", "irate", "maybe"], v: ["odium", "foamy", "liege"] },
  { h: ["rides", "nicer", "style"], v: ["ranks", "decoy", "spree"] },
  { h: ["quell", "amass", "moths"], v: ["qualm", "exact", "lists"] },
  { h: ["elfin", "ticks", "yells"], v: ["entry", "focal", "noses"] },
  { h: ["cowed", "ideal", "slyly"], v: ["coins", "weedy", "delay"] },
  { h: ["zebra", "nouns", "surge"], v: ["zones", "bluer", "aisle"] },
  { h: ["jaded", "coast", "sated"], v: ["jacks", "dealt", "dated"] },
  { h: ["gifts", "arena", "sedge"], v: ["goats", "freed", "snare"] },
  { h: ["leapt", "cotes", "discs"], v: ["lucid", "antes", "tests"] },
  { h: ["bogus", "evoke", "tanks"], v: ["blent", "groin", "seeks"] },
  { h: ["posts", "regal", "ensue"], v: ["purse", "signs", "salve"] },
  { h: ["nosed", "craze", "steed"], v: ["necks", "slave", "dread"] },
  { h: ["bucks", "anvil", "sores"], v: ["bears", "cover", "sales"] },
  { h: ["yards", "urged", "godly"], v: ["young", "rigid", "sadly"] },
  { h: ["queer", "asset", "solid"], v: ["quays", "easel", "rated"] },
  { h: ["vests", "serve", "rebel"], v: ["visor", "scrub", "shell"] },
  { h: ["sigma", "upper", "dodge"], v: ["sound", "gaped", "agree"] },
  { h: ["desks", "steel", "dingy"], v: ["dosed", "stern", "sally"] },
  { h: ["crept", "usage", "hater"], v: ["cough", "exalt", "their"] },
  { h: ["hosts", "bleed", "yarns"], v: ["hobby", "swear", "sides"] },
  { h: ["halls", "nudge", "sieve"], v: ["hands", "ladle", "siege"] },
  { h: ["magic", "loose", "needs"], v: ["melon", "globe", "crews"] },
  { h: ["vowed", "awake", "seeds"], v: ["vials", "weave", "dress"] },
  { h: ["swamp", "autos", "faced"], v: ["staff", "antic", "posed"] },
  { h: ["excel", "groan", "ruder"], v: ["eager", "cloud", "lunar"] },
  { h: ["gases", "email", "tiers"], v: ["greet", "spare", "sells"] },
  { h: ["bland", "learn", "scene"], v: ["bales", "abase", "dance"] },
  { h: ["cages", "exile", "eject"], v: ["crepe", "guise", "sweat"] },
  { h: ["pasha", "knave", "reset"], v: ["poker", "seats", "avert"] },
];
